// =============================================================================
// Property catalogue — STRUCTURE only. All names/descriptions live in i18n at
// `properties.items.<id>.*`. Imagery uses real, self-hosted stock photography
// in `public/properties/` (downloaded via scripts/fetch-photos.mjs, Unsplash
// License). These are DEMO stock photos, not the actual properties — replace
// with official photography for production (see TODO.md / compliance page).
// =============================================================================
import type { Property } from '~/types'

/** Map a hero + gallery photo id (public/properties/<id>.jpg) to media paths. */
const photo = (hero: string, ...gallery: string[]) => ({
  poster: `/properties/${hero}.jpg`,
  gallery: gallery.map((g) => `/properties/${g}.jpg`),
})

export const properties: Property[] = [
  {
    id: 'serene-villa',
    slug: 'serene-villa',
    collection: 'villa',
    status: 'available',
    price: 14_500_000_000,
    bedrooms: 4,
    bathrooms: 5,
    areaBuilt: 420,
    areaLand: 650,
    features: ['pool', 'garden', 'smart-home', 'security', 'view', 'parking'],
    featured: true,
    hue: 158,
    ...photo('p01', 'p02', 'p05'),
  },
  {
    id: 'canopy-villa',
    slug: 'canopy-villa',
    collection: 'villa',
    status: 'ready',
    price: 11_900_000_000,
    bedrooms: 3,
    bathrooms: 4,
    areaBuilt: 360,
    areaLand: 540,
    features: ['garden', 'pool', 'solar', 'home-office', 'parking'],
    featured: true,
    hue: 142,
    ...photo('p00', 'p06', 'p11'),
  },
  {
    id: 'lumen-villa',
    slug: 'lumen-villa',
    collection: 'villa',
    status: 'available',
    price: 16_800_000_000,
    bedrooms: 4,
    bathrooms: 4,
    areaBuilt: 445,
    areaLand: 700,
    features: ['pool', 'spa', 'smart-home', 'view', 'security', 'concierge'],
    featured: true,
    hue: 172,
    ...photo('p03', 'p13', 'p08'),
  },
  {
    id: 'ivory-terrace',
    slug: 'ivory-terrace',
    collection: 'residence',
    status: 'ready',
    price: 6_300_000_000,
    bedrooms: 3,
    bathrooms: 3,
    areaBuilt: 210,
    areaLand: 180,
    features: ['garden', 'parking', 'smart-home', 'security'],
    featured: true,
    hue: 44,
    ...photo('p19', 'p20', 'p05'),
  },
  {
    id: 'saffron-court',
    slug: 'saffron-court',
    collection: 'residence',
    status: 'available',
    price: 7_450_000_000,
    bedrooms: 3,
    bathrooms: 4,
    areaBuilt: 245,
    areaLand: 200,
    features: ['garden', 'home-office', 'parking', 'solar', 'security'],
    featured: false,
    hue: 38,
    ...photo('p04', 'p21', 'p08'),
  },
  {
    id: 'meridian-garden',
    slug: 'meridian-garden',
    collection: 'residence',
    status: 'offplan',
    price: 5_900_000_000,
    bedrooms: 2,
    bathrooms: 3,
    areaBuilt: 185,
    areaLand: 160,
    features: ['garden', 'gym', 'smart-home', 'parking'],
    featured: false,
    hue: 96,
    ...photo('p14', 'p11', 'p17'),
  },
  {
    id: 'skyline-crown',
    slug: 'skyline-crown',
    collection: 'penthouse',
    status: 'available',
    price: 22_500_000_000,
    bedrooms: 3,
    bathrooms: 4,
    areaBuilt: 320,
    areaLand: 0,
    features: ['view', 'rooftop', 'concierge', 'smart-home', 'gym', 'security'],
    featured: true,
    hue: 205,
    ...photo('p13', 'p18', 'p17'),
  },
  {
    id: 'celestia',
    slug: 'celestia-penthouse',
    collection: 'penthouse',
    status: 'ready',
    price: 27_800_000_000,
    bedrooms: 4,
    bathrooms: 5,
    areaBuilt: 380,
    areaLand: 0,
    features: ['view', 'rooftop', 'spa', 'wine-cellar', 'concierge', 'smart-home'],
    featured: false,
    hue: 225,
    ...photo('p18', 'p21', 'p02'),
  },
  {
    id: 'highland-manor',
    slug: 'highland-manor',
    collection: 'estate',
    status: 'available',
    price: 34_000_000_000,
    bedrooms: 5,
    bathrooms: 6,
    areaBuilt: 620,
    areaLand: 1400,
    features: ['pool', 'garden', 'wine-cellar', 'security', 'parking', 'view'],
    featured: true,
    hue: 128,
    ...photo('p10', 'p06', 'p13'),
  },
  {
    id: 'riverstone',
    slug: 'riverstone-estate',
    collection: 'estate',
    status: 'offplan',
    price: 41_500_000_000,
    bedrooms: 6,
    bathrooms: 7,
    areaBuilt: 780,
    areaLand: 2100,
    features: ['pool', 'garden', 'spa', 'gym', 'concierge', 'security'],
    featured: false,
    hue: 188,
    ...photo('p09', 'p16', 'p12'),
  },
  {
    id: 'azure-cliff',
    slug: 'azure-cliff-villa',
    collection: 'villa',
    status: 'available',
    price: 18_900_000_000,
    bedrooms: 4,
    bathrooms: 5,
    areaBuilt: 460,
    areaLand: 720,
    features: ['pool', 'view', 'smart-home', 'spa', 'security', 'parking'],
    featured: false,
    hue: 196,
    ...photo('p07', 'p12', 'p02'),
  },
  {
    id: 'palma-grove',
    slug: 'palma-grove',
    collection: 'residence',
    status: 'ready',
    price: 8_200_000_000,
    bedrooms: 3,
    bathrooms: 4,
    areaBuilt: 260,
    areaLand: 220,
    features: ['garden', 'pool', 'smart-home', 'parking', 'solar'],
    featured: false,
    hue: 76,
    ...photo('p15', 'p06', 'p20'),
  },
]

/** Collections used for catalogue filtering. Labels resolve to i18n
 *  `properties.collections.<id>`. */
export const collections = ['villa', 'residence', 'penthouse', 'estate'] as const

/** Feature ids known to the catalogue → i18n `properties.features.<id>`. */
export const featureIds = [
  'pool', 'garden', 'smart-home', 'security', 'view', 'parking',
  'solar', 'home-office', 'spa', 'concierge', 'gym', 'rooftop', 'wine-cellar',
] as const
